package com.iot.scenes;

public enum ScenesNames
{
    MAIN,
    CONNECTION,
    CONTACT,
    SERVICE,
    AUTHORIZATION,
    CONFIRM_PASSWORD,
    RESET_PASSWORD,
    ADVANCED_SERVICE,
    MAIN_SERVICE,
    MAIN_AUTHORIZATION,
    AUTHORIZATION_ADVANCED,
    AUTHORIZATION_MAIN_SERVICE
}
